### ISSUE TITLE
Access to the Id

### ISSUE THREAD

**Issue by Flexin1981** [dabapps/django-log-request-id#20]
Hey Guys,

Firstly this is a great project, I can't believe this isn't baked into Django already. 

not even sure that this is an issue but I would like to access the ID that is generated so that i can put it in a Json response so that users can give this to the team for tshooting, how can I access this from the view perspective ?

Thanks

**Comment by Flexin1981** [comment]
Sorry Guys, 

You can ignore this one, found it in the request.

Thanks again.

**Comment by imranariffin** [comment]
@Flexin1981 Can you share how did you find in the request? I've been trying to access the request id inside a view too, but couldn't find a way to do so. Your sharing it here would be a big help to me, and probably some other people too!

Thanks!

**Comment by imranariffin** [comment]
Ok, just learned from this [PR](https://github.com/dabapps/django-log-request-id/pull/16/files) that we can access it simply like this:
```python3
def some_view(request):
    request_id = request.id
```
