### ISSUE TITLE
Copyright outdated

### ISSUE THREAD

**Issue by guettli** [dabapps/django-log-request-id#22]
Thank you for this library.

BTW, the Copyright in the README is outdated:

> Copyright © 2012-2013, DabApps.

**Comment by j4mie** [comment]
Fixed, thanks!

**Comment by guettli** [comment]
@j4mie BTW, I read this some minutes ago: https://hynek.me/til/copyright-years/

And maybe you, too.

But: In the README there is still a year range.

**Comment by j4mie** [comment]
@guettli well spotted, removed from the README too. Thanks!
