### ISSUE TITLE
Does it support new-style middleware?

### ISSUE THREAD

**Issue by zivSher** [dabapps/django-log-request-id#23]
Hi, 
I noticed that the package uses MIDDLEWARE_CLASSES, which is the old style middleware. Does it support also new style?
Thanks.

**Comment by Checkroth** [comment]
I'm not the maintainer, but I just went through adding tests for py36 and django 1.11.

I assume you're talking about Django 2.0 middleware. I can tell you that the build for this project will fail for Django 2.0, and the library itself probably won't work with django 2.0 either.

You could always try adding it to a 2.0 project and paste the results here, but I wouldn't recommend using it for a version of django that it doesn't explicitly support.

**Comment by pzelnip** [comment]
I don't think the reporter was referring to Django 2.0.  Middleware changed in Django 1.10, see https://docs.djangoproject.com/en/1.10/topics/http/middleware/ which reads:

> Changed in Django 1.10:
> A new style of middleware was introduced for use with the new MIDDLEWARE setting. If you’re using the old MIDDLEWARE_CLASSES setting, you’ll need to adapt old, custom middleware before using the new setting. This document describes new-style middleware. Refer to this page in older versions of the documentation for a description of how old-style middleware works.

**Comment by RealOrangeOne** [comment]
> This issue can be closed as 1.3.2 version is working with new MIDDLEWARE settings and also Django 2.0 and later!

Correct!
