### ISSUE TITLE
Add Official Support for Python 3.6 and Django 1.11

### ISSUE THREAD

**Issue by Checkroth** [dabapps/django-log-request-id#26]
- To use this library with newer django projects, I would like official support for python 2.6 and Django 1.11
- I would also like to fix the Travis build to use Python 3.6.
  - Python 3.5 isn't a useful or common version to test on, and isn't available in the Travis build
- The tests use a deprecated `urlpatterns` tool which I would like to only rely on for older versions of Django
  - This tool was removed in Django 1.11, deprecated in Django 1.8

PR: https://github.com/dabapps/django-log-request-id/pull/25

**Comment by j4mie** [comment]
Fixed by #25, thanks!
