### ISSUE TITLE
Request ID is None

### ISSUE THREAD

**Issue by arjunnambiartc** [dabapps/django-log-request-id#28]
I am using Django2.1.3 and I have followed the exact same steps as described in the Readme.However, the request ID field comes as None as follows:
```
INFO     [2018-11-15 15:44:55,818] [none] connectivity_service.workflows.IPGroupCreateWorkFlow: {'status': 'IP Group created successfully on Junos Space'}
```
What could be wrong ??

**Comment by sshishov** [comment]
Probably you forgot to add middleware as described [here](https://github.com/dabapps/django-log-request-id#installation-and-usage)
