### ISSUE TITLE
Security Concerns

### ISSUE THREAD

**Issue by fescobar** [dabapps/django-log-request-id#52]
First of all, this tool is so useful for me. I appreciate too much your effort.

I'm using your package and I see there is no limitation in the length of the `X-Request-Id`. I mean I can send thousands of characters as id and that could affect the size of my logs. Could you establish a limit? I mean you could truncate the string if the length is major than the limit expected.

Also, it would be good if the name of the header `X-Request-Id` can be customized.

Thank you in advance.

**Comment by RealOrangeOne** [comment]
I believe using `X-Request-Id` is an opt-in behavior (see README for `LOG_REQUEST_ID_HEADER`). If you don't want the client affecting the request id, don't set that setting and you'll be set. This setting can also be used to change the name of the header at the same time.

Given that, I think it's fine that it be "up to you" to validate and sanitize the incoming request id as you wish. Whilst this library uses `uuid4` for request ids by default, they don't have to be, so putting in generic validation would be a rather breaking change.

If you do want to add validation, the best way would be to subclass the middleware, and override the `_get_request_id` method, as this is where the header is read from the request:

https://github.com/dabapps/django-log-request-id/blob/d87bfceb98c620e3dcedecfc11cd7fd5488424e1/log_request_id/middleware.py#L56

**Comment by fescobar** [comment]
@RealOrangeOne Thank you so much for your quick answer. I will try to override the method that you suggested to me.
