### ISSUE TITLE
Heroku request timeout and status=200

### ISSUE THREAD

**Issue by gadybadger** [dabapps/django-log-request-id#6]
I'm using django-log-request-id with Heroku, and I noticed in the logs that when I get H12 request timeouts from Heroku for any request ([due to 30 second time limit](https://devcenter.heroku.com/articles/request-timeout)), django-log-request-id registers it with status=200. The expected behavior should be to use status=503, which is what Heroku responds with. Here is an example:

```
Feb 25 09:33:19 my-app heroku/router:  at=error code=H12 desc="Request timeout" method=GET path="/my-url" host=my.host.com request_id=dad4ad83-0a55-447d-be83-28d6ea38bc55 dyno=web.1 connect=25ms service=30005ms status=503 bytes=0 
Feb 25 09:34:09 my-app app/web.1:  dad4ad83-0a55-447d-be83-28d6ea38bc55 [INFO] [middleware.process_response(36)]: method=GET path=/my-url status=200 user=4446
```

**Comment by j4mie** [comment]
(sorry for the delayed response)

I think this actually makes sense - your application has no way of knowing that Heroku has returned a 503. As far as it's concerned, it's merrily finished doing its work, and has no idea that Heroku's routing mesh has already told the client that the request has timed out. So a 503 from `heroku/router` and a 200 from `app/web` is correct.

**Comment by gadybadger** [comment]
I see, that does make sense. There is no way for the app to know that Heroku has already issued a 503. Thanks!
