### ISSUE TITLE
[Question] is it a common use case to use this with sentry?

### ISSUE THREAD

**Issue by simkimsia** [dabapps/django-log-request-id#60]
For production environments I mean

Would be great if there's documentation about using this with sentry if it's indeed a valid and common use case

**Comment by j4mie** [comment]
@simkimsia what do you mean exactly? This package is about logging rather than error reporting. Errors that end up in Sentry will already have a request ID attached, assuming the request ID is coming from an incoming HTTP header. Sorry if I've misunderstood the question!

**Comment by simkimsia** [comment]
Oh @j4mie no worries I think its all me

I could never get my head straight about logging and error reporting

Closing this

**Comment by j4mie** [comment]
No worries :) just shout if you have any more questions!
