### ISSUE TITLE
Replacing the text `request_id` to `correlation_id`

### ISSUE THREAD

**Issue by yass-arafat** [dabapps/django-log-request-id#61]
According to the current setup we are getting the log like this
`{"request_id": "49479a875c5b45439bf4e480efd7b0ec", "asctime": "2022-01-10 09:00:38,878", .....`
Is there any way to customise the text like
`{"correlation_id": "49479a875c5b45439bf4e480efd7b0ec", "asctime": "2022-01-10 09:00:38,878",`

**Comment by j4mie** [comment]
It depends on how you're generating those JSON logs but.. I think you should be able to write a custom log filter: copy and paste the code in `filters.py` and replace the line `request.request_id =` with `request.correlation_id =`. Does that work?

**Comment by yass-arafat** [comment]
Yes, it works. Thanks.
