### ISSUE TITLE
Generate/User Log Request id based on header.

### ISSUE THREAD

**Issue by prashantidealittechno** [dabapps/django-log-request-id#62]
Create a new log request id if not passed into the header, otherwise use the log_request_id that passed into the header for log.

In my case I am using the package in microservices to get the same log request id but how can I ensure that it does not generate the new log request id if the endpoint is called from another service and use the same one passed into the header, or ensure that if a new request is created by the user there will be no log request-id and we need to generate a new id.

**Comment by j4mie** [comment]
Hi 👋🏻 I'm not sure I fully understand the question, but I think what you're looking for is the `LOG_REQUEST_ID_HEADER` and possibly the `GENERATE_REQUEST_ID_IF_NOT_IN_HEADER` settings (see the README for details). Does that answer the question?

**Comment by prashantidealittechno** [comment]
I will add and check if I get the response I needed.

**Comment by prashantidealittechno** [comment]
it works  thanks
