### ISSUE TITLE
request_id in celery logs

### ISSUE THREAD

**Issue by dan-sparkes-cuboh** [dabapps/django-log-request-id#73]
Is there any way of getting the request_id from within celery tasks?

**Comment by RealOrangeOne** [comment]
Not explicitly, as once the task is running, there's nothing linking it back to the original request. If you need the request id as part of your task, you'll need to pass it explicitly

**Comment by dan-sparkes-cuboh** [comment]
sorry, having trouble getting the request_id from within my view
